### ISSUE TITLE
Install tinker 

### ISSUE THREAD

**Issue by alessandrofuda** [tastyigniter/flame#14]
**Expected behavior:**
Install Tinker via `composer require tinker` to Tastyigniter 2.1.1 

**Actual behavior:**
Error:  october/rain v1.0.469 requires laravel/tinker ~1.0

**Reproduce steps:**
`composer require tinker` from tastyigniter application

**Version:**
Tastyigniter 2.1.1

**Additional Information:**
To be update to october/rain 1.1.0 that require "laravel/tinker": "~2.0" (and not "laravel/tinker": "~1.0")

**Comment by sampoyigi** [comment]
Register the `Laravel\Tinker\TinkerServiceProvider::class` provider by adding it to your service providers here `app/system/providers.php` to use tinker.

**Comment by alessandrofuda** [comment]
it works thanks!
