### ISSUE TITLE
Manipulator __call method using in_array incorrectly

### ISSUE THREAD

**Issue by albanh** [tastyigniter/flame#15]
**Expected behavior:**
The $name variable should be searched for in the getAvailableGlideParameters array using in_array(needle,  haystack) ($name, $this->getAvailableGlideParameters()) 

**Actual behavior:**
It's the opposite way around resulting in an ErrorException "in_array() expects parameter 2 to be array, string given"

**Reproduce steps:**
Exception is generated after a fresh install and visiting /admin/settings/edit/general

**Version:**
v3.0.4-beta.22.4

**Additional Information:**
The initial error when visiting that page was a FileNotFoundException "Could not find the image `{path}/assets/media/uploads/no_photo.png`." even though the image was present

**Comment by sampoyigi** [comment]
Nice spot! Thank you for sharing. Also the initial error has been fixed in **v3.0.4-beta.23**
