### ISSUE TITLE
Flexible location schedule shows incorrect date

### ISSUE THREAD

**Issue by olieydt** [tastyigniter/flame#4]
**Expected behavior:**
Location should show next opening hours. If location is open, it should show todays schedule. If it is closed it should show the next available hours.

**Actual behavior:**
If location has a flexible schedule, it shows the next day's hours. In the picture below the system time is Sunday, 1:10pm. The schedule showed is incorrect, it is showing Monday, and it should show Sunday.

<img width="542" alt="Screen Shot 2020-04-19 at 1 04 43 PM" src="https://user-images.githubusercontent.com/15329812/79694538-d3ba3300-823e-11ea-867e-b452bf234b02.png">

**Reproduce steps:**
Create a location with flexible pickup hours. Set todays schedule to be different from tomorrows schedules. 

<img width="609" alt="Screen Shot 2020-04-19 at 1 04 50 PM" src="https://user-images.githubusercontent.com/15329812/79694497-8dfd6a80-823e-11ea-9714-2e12f32534d3.png">

**Version:**
Current master

**Additional Information:**

**Comment by sampoyigi** [comment]
Any chance this issue is related? https://forum.tastyigniter.com/d/1723-open-hours-showing-incorrectly

**Comment by sampoyigi** [comment]
Merged! 👍

**Comment by olieydt** [comment]
I haven't encountered that issue on my end!
