### ISSUE TITLE
Not Displaying the Open Times Correctly

### ISSUE THREAD

**Issue by cyberfingers** [tastyigniter/flame#6]
On the menu page - https://cyberfingers.net/tastyigniter/default/menus panel-local indicates the We are open but has 8:00 pm - 8:00 pm instead of 9:00 am -  8:00 pm.
![Opening Hours](https://user-images.githubusercontent.com/34279957/80402700-4903b480-888c-11ea-9fe6-1dffb2d9d380.jpg)

![Menu - Displays Wrong Open Hours](https://user-images.githubusercontent.com/34279957/80402709-4e60ff00-888c-11ea-8af7-b569839befcd.jpg)

**Comment by sampoyigi** [comment]
Is it related to #4?

**Comment by cyberfingers** [comment]
Hi Sam,

This is an issue which might be preventing visitors from placing orders. If
code could be changed to not display time until problem can be resolved
this would be a good temporary solution.

Also another critical issue is the EU cookie warning. This blocks uses from
continuing to place orders, as it covers up the continue button.

These are issues which I think prevent visitors from placing orders.

Thanks, David

**Comment by sampoyigi** [comment]
Did you try the fix from #4? You can also start a new discussion on the forum or open a new issue here if you haven't for the EU cookie issue.

**Comment by cyberfingers** [comment]
Hi Sam,

I will look into it and get back to you, for now I turned it off.

Thanks
